== Abord conjoint de l'obésité à travers la méthode scientifique occidentale et la médecine traditionnelle chinoise.

Maigrir & Métal - Tutoriel pour les professionnels de l’amaigrissement.

=== Préface

La surcharge pondérale représente un problème de santé publique important. Cette affection chronique représente une source majeure de mortalité précoce. Suivant son degré le recul de l’espérance de vie varie de 6 à 15 ans. Du point de vue des traitements, seule la chirurgie bariatrique semble donner de bons résultats à long terme mais cela au prix d’une amputation irréversible souvent drastique et d’effets secondaires non négligeables.

Les solutions médicales et nutritionnelles sont, quant à elles, ridicules, inefficaces et parfois dangereuses et ce depuis des décennies. Les seuls domaines dans lesquels ces solutions excellent sont l’entretien de la confusion, l’extravagance, l’inefficacité et parfois le succès médiatique. Force est de constater qu’elles ne sont que le fruit de l’imagination de personnes n’ayant la plupart du temps aucune compétence dans le domaine de la médecine, de la physiologie humaine et surtout de la nutrition, fussent-elles pour certaines, médecins.

Il est assez navrant par ailleurs de constater qu’aucun chercheur, médecin ou nutritionniste ne soit arrivé jusqu’à maintenant à élaborer une méthode logique simple, compatible avec les données scientifiques actuelles, efficace et sans danger vis à vis de cette affection. De fait, c’est l’existence même de cette carence à cet endroit qui fait la place aux incompétents. Cet état de fait nous laisse présager encore pour longtemps de récurrents printemps qui apporteront une fois de plus leur lot de nouveaux régimes farfelus et dont le dernier en date qui marque encore les esprits, a quand même laissé quelques insuffisances rénales graves et mortelles derrière lui.

Le propos étant surtout destiné aux professionnels de la santé et de la nutrition, il se peut que cet écrit soit peu propice à la vulgarisation. C’est le cas en effet dans le sens où le vocabulaire des métiers médicaux ainsi que les pré requis en terme de connaissance créent de facto une ségrégation du lectorat. Pour expliciter son propos vis à vis des scientifiques, il utilise les termes et les notions acquises dès les premières années de médecine, en l’occurence les connaissances fondamentales en biochimie, en physiologie et en nutrition humaine telles qu’elles ont été décrites depuis maintenant un bon demi siècle et qui, de fait, sont désormais solidement établies. Pour la Tradition Chinoise, il emprunte à l’ensemble du corpus taoïste.footnote:[Taoisme = Une certaine vision du monde.], mais surtout à la Loi des 5 éléments - chinois simplifié : 五行 ; pinyin : wǔxíng - qui est l’un des grands obligatoires de la médecine chinoise et que l’on définira rapidement comme une structure de catégorisation du monde grâce à une pensée analogique logique.


|===

| ressources d'énergie | glucides | lipides

| stockage | foie | peau & séreuses

| mise en oeuvre | rapide & instantanée | lente & tardive

| réserves | petites | très importantes jusqu'à énormes

| importance | 70% | 30%

| molécule de stockage | http://jean-jacques.auclair.pagesperso-orange.fr/polysaccharides/glycogene.htm[glycogène] (énorme)| triglycérides (petite)

| mise en circulation | libre | liée à des protéines

| métablisme | indépendant | lié aux glucides

|===

Aborder la médecine chinoise nécessite d'en connaître un peu à propos du symbolisme ayant trait au taoïsme.
Contrairement à la démarche scientifique qui part de l'observation d'un phénomène pour en déduire une loi dont on vérifiera les résultats pour ou non valider la loi, la démarche taoïste observe et classifie les phénomènes à travers des systèmes symboliques très précis et se contente d'appliquer les lois qui régissent ces systèmes symboliques
En gros, pour situer la différence entre médecine chinoise et médecine scientifique, la première définit le monde et les phénomènes qu'il contient en terme de symboles. Il applique les lois qui régissent les symboles.
