== Abord conjoint de l'obésité à travers la méthode scientifique occidentale et la médecine traditionnelle chinoise.

Maigrir & Métal - Tutoriel pour les professionnels de l’amaigrissement.

=== Titres envisagés
En Chine, l’obésité est une maladie de peau.

Traité du zen et de l'entretien des motocyclettes
Traité du tao et de la perte de poids
Traité du tao et de l’amaigrissement
Traité du tao et de l’amincissement
Traité du tao et de la minceur
Maigrir - Manuel d’utilisation
L’obésité, une maladie de peau ?
Quoique cocasse, cette question mérite réflexion.
Maigrir - Manuel d’utilisation
Maigrir au masculin - Manuel d’utilisation.
L’obésité, une sorte de maladie de peau ?
Maigrir pour les hommes
Maigrir mode d’emploi


=== Préface 1
=== Préface

La surcharge pondérale représente un problème de santé publique important. Cette affection chronique représente une source majeure de mortalité précoce. Suivant son degré le recul de l’espérance de vie varie de 6 à 15 ans. Du point de vue des traitements, seule la chirurgie bariatrique semble donner de bons résultats à long terme mais cela au prix d’une amputation irréversible souvent drastique et d’effets secondaires non négligeables.

Les solutions médicales et nutritionnelles sont, quant à elles, ridicules, inefficaces et parfois dangereuses et ce depuis des décennies. Les seuls domaines dans lesquels ces solutions excellent sont l’entretien de la confusion, l’extravagance, l’inefficacité et parfois le succès médiatique. Force est de constater qu’elles ne sont que le fruit de l’imagination de personnes n’ayant la plupart du temps aucune compétence dans le domaine de la médecine, de la physiologie humaine et surtout de la nutrition, fussent-elles pour certaines, médecins.

Il est assez navrant par ailleurs de constater qu’aucun chercheur, médecin ou nutritionniste ne soit arrivé jusqu’à maintenant à élaborer une méthode logique simple, compatible avec les données scientifiques actuelles, efficace et sans danger vis à vis de cette affection. De fait, c’est l’existence même de cette carence à cet endroit qui fait la place aux incompétents. Cet état de fait nous laisse présager encore pour longtemps de récurrents printemps qui apporteront une fois de plus leur lot de nouveaux régimes farfelus et dont le dernier en date qui marque encore les esprits, a quand même laissé quelques insuffisances rénales graves et mortelles derrière lui.

Le propos étant surtout destiné aux professionnels de la santé et de la nutrition, il se peut que cet écrit soit peu propice à la vulgarisation. C’est le cas en effet dans le sens où le vocabulaire des métiers médicaux ainsi que les pré requis en terme de connaissance créent de facto une ségrégation du lectorat. Pour expliciter son propos vis à vis des scientifiques, il utilise les termes et les notions acquises dès les premières années de médecine, en l’occurence les connaissances fondamentales en biochimie, en physiologie et en nutrition humaine telles qu’elles ont été décrites depuis maintenant un bon demi siècle et qui, de fait, sont désormais solidement établies. Pour la Tradition Chinoise, il emprunte à l’ensemble du corpus taoïste.footnote:[Taoisme = Une certaine vision du monde.], mais surtout à la Loi des 5 éléments - chinois simplifié : 五行 ; pinyin : wǔxíng - qui est l’un des grands obligatoires de la médecine chinoise et que l’on définira rapidement comme une structure de catégorisation du monde grâce à une pensée analogique logique.

=== Préface 2

Maigrir, c’est comme pour l’essence dans une voiture. Si on veut baisser la jauge, il faut prendre l’autoroute et rouler et rouler, mais en plus, faut oublier de passer à la pompe !
Cette image à l’emporte-pièce a le mérite d’être simple, concise et surtout frappée au coin du bon-sens. Compréhensible par tout conducteur, elle illustre de manière adéquate le fonctionnement des machines thermiques dont les éléments principaux sont le carburant, le réservoir et le moteur flanqué de son carburateur.
Lorsque l’on assimile l’organisme à une machine thermique, la nourriture représente le carburant et les organes qui utilisent l’énergie contenue dans la nourriture représentent le moteur. Si la quantité de nourriture absorbée dépasse la quantité d’énergie dépensée par les organes, l’organisme met en réserve le surplus en grossissant. Dans le cas contraire, l’organisme puise dans ses réserves en maigrissant.
Ce principe, juste au demeurant si l’on s’en tient aux principes de la thermodynamique, est un peu trop simpliste quand vient le moment de l’appliquer à la machine humaine. La nourriture est un carburant complexe composé d’aliments qui sont totalement différents les uns des autres, ces aliments sont eux-même composés de molécules différentes, des protides, des glucides, des lipides, des oligo-éléments, vitamines, minéraux, etc. En raison de cette complexité, quelle type de substances vais-je privilégier dans ce régime ? Les protides, les lipides, les sucres lents ? les sucres rapides ? Vais-je m’abstenir de manger et faire un jeûne ? un jeûne intermittent ? Combien d’eau faut-il boire ? De quelle manière vais-je dépenser mon énergie ? sport aérobique ?  anaérobique ? lentement et longtemps ou intensif avec de courtes récupérations ? Dois-je aller courir à jeun ? Faut-il manger des féculents le soir ? A quelle heure dois-je manger ? Un lot de questions qui méritent des réponses précises ou mieux, une explication du phénomène que représente l’organisme vu comme une machine thermique compliquée.
Pour décrire cette machine et son fonctionnement, deux abords sont utilisés, celui de la médecine scientifique actuelle et celui de la médecine chinoise traditionnelle.
L’abord scientifique utilise les termes et les notions acquises dès les premières années de médecine, en l’occurence les connaissances fondamentales en biochimie, en physiologie et en nutrition humaine qui sont solidement établies. Il permet de se faire une idée précise de la machine, de comprendre ses mécanismes, ses fonctions, la manière dont ça marche.
L’abord chinois, plus précisément taoïste, issu d’une pensée qui manipule l’analogie de préférence à l’analyse, permet d’intégrer et de comprendre les éléments de la machine humaine et leur fonctionnement sous un angle différent mais parfaitement complémentaire à la démarche scientifique. L’élément principal du corpus taoïste.[1] qui est utilisé pour la compréhension du sujet est la loi des 5 éléments - 五行 (chinois simplifié) ; wǔxíng (pinyin). Ce système symbolique est l’un des grands obligatoires de la médecine chinoise et on le définira rapidement comme une structure de catégorisation du monde grâce à une pensée analogique logique.
La première complexité de la structure humaine vue sous l’angle d’une machine thermique est qu’elle est en fait composée de deux machines thermiques. Celles-ci sont couplées pour tendre ensemble à la même finalité, à savoir produire de l’énergie mais ceci à l’aide de structures, de substances, de quantités, de puissance et de bien d’autres choses encore, très différentes pour chacune des deux machines.
Cette structure particulière présentant un fonctionnement qui peut paraître complexe, apparaîtra toutefois plus facilement compréhensible aux conducteurs qui font la distinction entre une voiture à essence et une voiture au diesel. Ceci en terme de conduite s’entend, et non de prix à la pompe.
Il faut imaginer la machine humaine comme une voiture hybride. Elle possède deux moteurs mais contrairement aux hybrides actuels de type thermique/électrique, celui de la machine humaine est essence/diesel.
Avec cette voiture le conducteur peut faire face à tout type de conduite. Avec le moteur à essence, il se permet des démarrages fulgurants exploitant la puissance du moteur dès le départ, il profite de la puissance disponible sous l’accélérateur pour dépasser, avaler les virages. Seule l’essence, produit volatil qui s’enflamme facilement dans des moteurs lui permettant de monter dans les tours, permet ce genre de conduite sportive.
Avec le moteur diesel, l’allumage nécessite de faire chauffer la bougie, car le gasoil, dérivé des huile lourdes est plus difficile à enflammer, nécessite d’être chauffé au démarrage. Le moteur ne tourne pas très rapidement mais possède un fort couple à bas et moyen régime, l’idéal pour propulser une confortable berline aux vitesses autorisées pendant de longues heures d’autoroute.
Deux styles de conduite à l’opposé l’une de l’autre avec des carburants différents, des stockages différents, un moteur ne fonctionnant pas de la même manière, pollution différentes.



Pour son fonctionnement, le corps humain dispose de deux moteurs différents. Pour facilité la compréhension, il est intéressant de créer une analogie entre ces deux moteurs et les motorisations essence et diesel que nous trouvons dans nos véhicules.

|===

| ressources d'énergie | glucides | lipides

| stockage | foie | peau & séreuses

| mise en oeuvre | rapide & instantanée | lente & tardive

| réserves | petites | très importantes jusqu'à énormes

| importance | 70% | 30%

| molécule de stockage | http://jean-jacques.auclair.pagesperso-orange.fr/polysaccharides/glycogene.htm[glycogène] (énorme)| triglycérides (petite)

| mise en circulation | libre | liée à des protéines

| métablisme | indépendant | lié aux glucides

|=== 
=== Bref rappel du symbolisme chinois

Le monde taoïste se décrit à l'aide d'un ensemble de systèmes symboliques interdépendants. Les symboles de ces systèmes sont les chefs de file emblématiques de classifications dans des domaines aussi variés que l'agriculture, l'astronomie, la médecine, la musique, l'art culinaire, l'art pictural, la danse, la bien-séance. Dans chacun de ces domaines les choses sont décrites à travers le sytème symbolique et s'organisent suivant ses lois. 


La tradition taoïste décrit le monde à l'aide d'un ensemble de systèmes symboliques interdépendants. Les symboles de ces différents systèmes sont les chefs de file emblématiques de classifications appartenant à des domaines aussi divers et variés que l'agriculture, l'astronomie, la médecine, la musique, l'art culinaire, la bien-séance. Dans chacun de ces domaines, ce sont les mêmes symboles qui oeuvrent et les mêmes lois qui organisent. 



Chacune des choses ou des phénomènes appartenant à ces domaines apparaît liés aux symboles et s'organisent à l'aide des mêmes lois. 
La tradition taoïste décrit le monde à l'aide d'un ensemble de systèmes symboliques interdépendants. Les symboles de ces différents systèmes sont les chefs de file emblématiques de classifications appartenant à des domaines aussi divers et variés que l'agriculture, l'astronomie, la médecine, la musique, l'art culinaire, la bien-séance. Chacunes des choses appartenant à ces domaines sont relié aux symboles et s'organisent à l'aide des mêmes lois. 




=== Définition et physiopathologie de l'obesité en médecine chinoise

La surcharge pondérale correspond à une hypertrophie du tissu adipeux. Du point de vue scientifique, le tissu adipeux est donné comme étant situé sous la peau et n'y est pas véritablement relié ne serait-ce qu'en terme de fonction de protection tandis qu'en MTC fait partie intégrante de l'organe peau.

A ce moment, il convient  de préciser l'importance de la notion d'organe ou Tsang (Zang  脏) en MTC.
Un Tsang est une structure vitale essentielle sans qui aucune vie n'est possible. Leur destruction, ablation est synonyme de mort, instantanée pour certains Tsang, plus tardives pour d'autres mais inéluctable. 
Ceci les différencie des Fu, entrailles, qui traitent avec l'extérieur  Les Tsangs, situés profondément au sein de l'organisme, traitant les fonctions  essentielles, parfaitement dirigés vers l'interne sont gouvernés par la loi des 5 éléments.


L’obésité, la surcharge pondérale grasse, correspond en médecine chinoise à un déséquilibre caractérisé des deux éléments qui constituent l’axe horizontal de la loi des 5 éléments, les éléments Bois et Métal. La balance entre ces deux éléments est perturbée par l’existence d’un excès vicieux portant sur l’élément Métal associé à une carence plus ou moins prononcée de l’élément Bois et parfois de l’élément Eau.

L’excès de l’élément Métal est patent du fait que la maladie se caractérise essentiellement par l’hypertrophie du tissu adipeux que constitue une partie fonctionnelle de l’organe qu’est la peau. Celle-ci, comme le poumon - qui n’en n’est que son équivalent interne - fait partie de l’élément Métal qui assure principalement la fonction respiratoire. Etant même essentielle au maintien de la vie, elle est classée dans la catégorie des Tsang, les Organes Vitaux. En-dehors de la fonction respiratoire, elle possède par ailleurs une fonction de protection ; protection contre les agressions mécaniques du milieu extérieur mais aussi et surtout contre les variations thermiques, en particulier le froid.

Il est assez facile de mettre en évidence les analogies qui caractérisent l’élément Métal. Alors que le printemps fait germer, que l’été fait pousser, que la fin d’été amène à maturation, l’automne correspond à la saison des récoltes. Le Métal c’est la saison des cueillettes, des moissons et autres vendanges et des charcuteries, celle où on mange et on grossit avant l’arrivée de l’hiver et ses froidures. Etre plus gras à la fin de l’automne est physiologiquement normal et pour les périodes antérieures au chauffage central et autres pompes à chaleur, une véritable nécessité. Le gras, carburant lipidique stocké au niveau des adipocytes du tissu adipeux sous cutané est destiné à être utilisé tout au long de l’hiver et du printemps pour faire face au froid et à la disette de cette partie de l’année. Ce qu’il faut retenir à l'issue cette simple constatation analogique est que l’automne fait grossir, l’hiver et le printemps font maigrir. Rapporté aux éléments, le Métal fait grossir tandis que L’Eau et le Bois font maigrir.

Si l’augmentation de la tonalité de cet élément en automne est perçue comme normale, une alimentation et un comportement teintés en continu de l’empreinte de élément Métal aura pour conséquence de faire passer cet élément en excès vicieux. Vicieux car l’excès est constant et sans variation tout au long du temps, entraînant une souffrance des autres éléments. A ce point, la maladie est arrivée à son stade chronique.

De fait, un élément vicieux possède évidemment un comportement vicié. Par rapport aux autres éléments du cycle, dans le cadre du cycle Cheng, il refuse l’énergie de sa mère, la Terre et ne la transmet pas à l’Eau, son fils ; dans le cadre du cycle Keu, il refuse le contrôle de son dominant, le Feu et il agresse fortement son dominé, le Bois.

En tant compte des relations entre les éléments du cycle, son traitement est des plus classiques et consiste simplement à carencer l’élément Métal tout en surchargeant les éléments Bois en priorité et Eau secondairement. Ce profil de traitement doit être maintenu jusqu’à retour à la classique carence primitive du Métal, celle-ci bénéficiant ensuite de la prescription d’un classique régime de type Terre, régime équilibré en fonction des saisons, pour être comblée.

A première vue, l’obésité se caractérise essentiellement par un dépôt excessif de triglycérides au niveau de la peau et des séreuses. Ces deux tissus font partie de l’élément Métal. Le chinois n’y va pas quatre chemins, excès dans la peau, excès de l’élément Métal.
Ces deux tissus, pour des raisons liées surtout à la protection et à la défense contre le froid sont susceptibles de stocker de manière plus ou moins importante le carburant lipidique sous forme de triglycérides stockés dans les adipocytes du panicule sous-cutané et des séreuses. Ce carburant lipidique sera consommé tout au long de l’hiver et du printemps pour faire face au froid et à la disette du moment. La saison du printemps fait germer, l’été fait pousser, la fin d’été fait murir et l’automne recueille. C’est la saison des cueillettes, des moissons et autres vendanges, celle où on mange et on grossit avant l’arrivée de l’hiver et ses froidures. Etre plus gras à la fin de l’automne est normal. Il y a une variation normale de la variation de l’élément Métal qui se produit normalement à l’automne. 

La seule manière intelligente de concevoir le problème de la surcharge pondérale est de l’aborder sous l’angle de la gestion de l’énergie du corps humain. 
Deux éléments sont essentiels dans la gestion de l’énergie du corps humain. L’élément Métal est la réserve de lipides














Du point de vue physiologique le corps humain utilise deux ressources énergétiques pour faire face à ses besoins. Ces deux ressources sont représentées par les glucides et par les lipides. Dans le cadre d’une diète normo-calorique et normo-équilibrée par rapport aux besoins, les protides sont considérés comme nutriments plastiques et ne font pas partie des ressources énergétiques. Ils n’ont ce rôle uniquement lors de périodes particulières comme le jeûne, la dénutrition et au cours d’autres agressions chirurgicales observées en réanimation. Dans ce cas, le corps se « mange » lui-même en détruisant ses propres tissus. Le tissu musculaire en première ligne mais les autres tissus aussi au fur et à mesure du jeûne qui n’est tout compte fait qu’une autolyse.




L’examen des qualités de ces deux ressources montrent qu’à l’instar de l’opposition Bois/Métal des 5 éléments, celles-ci apparaissent systématiquement  asymétriques à l’exception du fait qu’elles aboutissent toutes les deux à la même molécule,




Le glycogène issu du glucose provenant de la digestion des aliments contenant de l’amidon est stocké au niveau du foie et des muscles. Aucune autre cellule n’est douée de cette capacité de stockage et ne peut qu’utiliser le glucose. Le foie stocke le glycogène pour l’ensemble des cellules du corps humain tandis que les cellules musculaires stockent le glycogène uniquement pour elles-mêmes. De par ses deux lieux de stockage spécifiques, le foie et les muscles, on reconnait immédiatement l’appartenance des sucres (glycogène - glucose) à l’élément Bois. A noter que le glycogène représente la forme de stockage au sein des cellules, le glucose qui en est issu n’est que la forme soluble qui permet le transport sanguin et uniquement celui-ci. Pour donner une idée nous n’avons en tout et pour tout que 6 à 10 g de sucre circulant à raison de 6 à 10 litres de sang contenant 1 g de glucose par litre. La quantité journalière de glycogène hépatique et musculaire est de l’ordre de l’ordre 165 g environ dans le cadre d’une alimentation équilibrée de l’ordre de 2400 Kcal/J.
Les triglycérides apportés par l’alimentation, véhiculés à travers le corps sur les protéines de transport, sont apportés et stockés au sein du tissu adipeux et aussi au niveau des séreuses. Ces deux lieux de stockage spécifiques, la peau et les séreuses, sont représentatifs de l’élément Métal. Il faut préciser que les séreuses peuvent facilement être classées dans l’élément Métal dans le sens où elles représentent « la peau » des organes et sont douées comme la peau de la fonction de protection de l’organe qu’elles entourent (péricarde, plèvre, épiploon).
Nous disposons donc de deux ressources énergétiques, les sucres et les graisses qui sont en relation directe avec les éléments Bois et Métal situés sur l’axe horizontal de la loi des 5 éléments.
La surcharge pondérale correspond à une réserve d’énergie stockée de manière excessive au sein du tissu adipeux sous-cutané et au sein des viscères par le biais des séreuses correspond donc à un excès de Métal.









































中国五行和肥胖
金
木
金属木材











« Maigrir, c’est pareil que dans une voiture. Si tu veux faire baisser le niveau dans le réservoir, tu prends l’autoroute et puis tu roules, dans le genre tu t’arrêtes pas, mais en plus, faut pas passer à la pompe ! »
Bon okay, c’est un peu à l’emporte-pièce mais c’est concis, imagé et frappé au coin du bon-sens et ça illustre bien la méthode qu’il faut mettre en oeuvre pour maigrir.

J’ai l’habitude d’utiliser l’analogie avec un véhicule et la manière de dépenser son carburant pour faire comprendre ce que représente un amaigrissement parce que cela correspond à des réalités qui sont tangibles aux personnes à qui je m’adresse et surtout parce que cela me permet d’étiqueter ces idées du sceau du bon sens. Et dans ce sens, c’est très clair.
Il faut se représenter le corps humain comme un véhicule, une automobile par exemple. Dans ce véhicule, on peut reconnaître une structure comme le châssis, les roues, des amortisseurs, l’habitacle avec tout ce qu’il contient, les fauteuils, le tableau de bord avec ses instruments et un moteur qui fournit l’énergie motrice à partir de la combustion du carburant situé dans le réservoir. Par ailleurs, dans un organisme, on peut reconnaître une structure contenant des tissus différents organisés en fonctions, des muscles qui fournissent une énergie motrice à partir de la combustion du carburant qui est stocké dans certains organes comme la peau (tissu adipeux pour le stockage des lipides) et comme le foie et les muscles eux mêmes (tissu hépatique et musculaire pour le stockage des sucres). 
Cette automobile est moderne, elle est hybride, c’est à dire qu’elle utilise deux moteurs. Mais c’est une hybride un peu spéciale, elle n’est pas du type essence/électrique comme c’est habituellement le cas mais essence/diesel. Un gros moteur à essence de type super-carburant couplé à un petit moteur à gasoil, un diesel.
Il va sans dire que les caractéristiques de ces deux moteurs ainsi que celles de leurs carburants respectifs sont totalement différentes, opposées et complémentaires. C’est ce que nous allons voir en détails après vous avoir demandé d’essayer d’imaginer que la réponse à la question « comment maigrir ? » puisse être du même genre que à la réponse à la question « Eh ! que pourrais-je bien faire pour vider mon réservoir de carburant ? ». Là on est vraiment tenté de répondre sans trop se tromper « C’est simple, mec ! Tu roules sans t’arrêter et tu cesses de passer à la pompe ! Panne sèche assurée ! » C’est précisément cette réponse que nous allons tenter, par analogies successives, de traduire en langage de nutritionniste.



























Le sujet principal de ce livre est la médecine chinoise. Pour explorer correctement celle-ci il est important d’expliquer dès le départ le type de notions que vous allez rencontrer.
Le type principal des notions utilisées en médecine chinoise est de nature symbolique. Les relations qui lient ces notions entre elles sont déduites par analogie. Les méthodes qui permettent d’utiliser ces notions sont des méthodes paradoxales.









L’étude du yin/yang est fondamentale pour la compréhension de la médecine chinoise. Ces deux termes définissent les deux pôles entre lesquels oscille le phénomène vivant. Le yin est de nature femelle, réceptif, moins mobile, moins rapide mais endurant. Le Yang est de nature mâle, émetteur, plus mobile, plus rapide mais rapidement épuisé. Le yin est à l’intérieur, le yang à l’extérieur. Le Yang est en haut à gauche et en avant, le yin est en bas à droite et en arrière.

Comprendre le Yin/Yang est fondamental. La première compréhension est facile d’abord. Elle consiste à repérer dans l’ensemble des choses qui nous entourent le caractère yin ou yang des propriétés qu’elles possèdent. Ceci doit se faire sur la base de notions basiques de la classification qui doivent être apprises et retenues. Ces bases fondamentales sont les suivantes :
yin : matériel, interne, bas, côté droit,  pesant, statique, essentiel, réceptif,







La période la plus propice à l’amaigrissement s’étend du début de l’hiver, en gros vers le mois d’octobre et s’étend sur deux saisons, l’hiver et le printemps, jusqu’à la fin du mois d’avril. C’est la période 














Il peut être tentant d’essayer de comprendre le problème de l’obésité en essayant d’accorder les visions que l’ont peut avoir de ce déséquilibre, à travers les prismes respectifs de la pensée chinoise et de la science occidentale. Ceci dans le domaine de la médecine et plus particulièrement à celui de la nutrition.
Pour ce qui est de la vision occidentale, nous sommes particulièrement bien documentés à travers des sources scientifiques dûment établies, vérifiées et considérées comme acquises. Nous aurons besoin de ces notions dans la compréhension du propos. Elles appartiennent pour la plupart aux domaines de l’anatomie, de la physiologie, de la physiopathologie, de la biochimie, de l’ergonomie et encore bien d’autres aspects.
Pour ce qui est de l’approche chinoise, il est impératif de bien connaître la pensée qui sous tend cette vision du monde particulière. C’est une approche beaucoup plus intuitive que déductive qui met à l’oeuvre essentiellement une pensée analogique. Elle apparaît de fait essentiellement comme un corpus de correspondances établies dans tous les domaines.
Cette médecine traditionnelle est bâtie essentiellement sur l’observation et l’analogie. Son postulat princeps réside dans le fait qu’étant insérés entre Ciel et Sol et d’une certaine manière, le fruit de leur union, notre structure et notre fonctionnement reflète nécessairement ces deux pôles à la fois. Que doit-on distinguer au niveau de ces deux pôles ? Essentiellement des jalons, comme les solstices, les équinoxes dans le Ciel, scandant le temps et des points cardinaux qui s’associent avec ces moments spéciaux du temps. Le sud et le nord avec leurs solstices respectifs, celui d’été et celui d’hiver, le plus chaud et le plus froid puis l’est et l’ouest avec leurs équinoxes respectifs, du printemps et de l’automne, ni chaud, ni froid, se ressemblant plutôt que de s’opposer, même température, même luminosité. Deux pôles opposés et deux pôles plutôt similaires

nous devons nécessairement exprimer dans notre structure et notre fonctionnement  le reflet des structures et du fonctionnement de ces deux pôles 

La méthode analogique qu’utilise le chinois est assez simple. Elle consiste essentiellement à repérer des éléments remarquables dans un système puis à rechercher les éléments remarquables qui leur corresponde dans un autre système.






